# Generated by Django 3.2.8 on 2021-12-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugid', models.IntegerField(primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.BooleanField()),
            ],
            options={
                'db_table': 'drug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('npi', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.BooleanField()),
                ('totalprescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'prescriber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescribercredential',
            fields=[
                ('npi', models.OneToOneField(db_column='npi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myDrugs.prescriber')),
                ('credential', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prescribercredential',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriberdrug',
            fields=[
                ('npi', models.OneToOneField(db_column='npi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myDrugs.prescriber')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescriberdrug',
                'managed': False,
            },
        ),
    ]
